---

- name: "Install pip."
  include: pip-install.yml

- name: "Retrieve pip executable path on Ubuntu."
  shell: command -v pip
  register: pip_bin_path
  when: ansible_distribution == "Ubuntu"

- name: "Retrieve pip2 executable path on macOS."
  shell: command -v pip2
  environment:
    # Workaround for macOS
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: pip_bin_path
  when: ansible_distribution == "MacOSX"

- name: "Install latest python packages."
  pip:
    name: "{{ item.name | default(item) }}"
    state: present
    version: "{{ item.version | default(omit) }}"
    executable: "{{ pip_bin_path.stdout | default(omit) }}"
    extra_args: --user
  with_items: "{{ python_packages }}"
  when: ansible_distribution == "Ubuntu"

- name: "Install latest python packages."
  pip:
    name: "{{ item.name | default(item) }}"
    state: present
    version: "{{ item.version | default(omit) }}"
    executable: "{{ pip_bin_path.stdout | default(omit) }}"
  environment:
    # Workaround for macOS
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ python_packages }}"
  when: ansible_distribution == "MacOSX"
